# Generated by Django 4.2.2 on 2023-07-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_date_alter_post_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(blank=True, verbose_name='계절'),
        ),
    ]
