# Generated by Django 4.2.2 on 2023-07-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(blank=True, null=True, verbose_name='계절'),
        ),
    ]
