# Generated by Django 4.2.2 on 2023-07-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_user_id_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.IntegerField(blank=True, null=True, verbose_name='여행일'),
        ),
    ]
