# Generated by Django 4.2.2 on 2023-07-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='perfume',
            table='perfume',
        ),
    ]
