# Generated by Django 4.2.2 on 2023-07-08 12:50

from django.db import migrations, models
import perfumes.models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0002_alter_perfume_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=perfumes.models.get_upload_path, verbose_name='이미지'),
        ),
    ]
