# Generated by Django 4.2.2 on 2023-07-12 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import musics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='노래 제목')),
                ('singer', models.CharField(max_length=50, verbose_name='가수')),
                ('image', models.ImageField(blank=True, null=True, upload_to=musics.models.get_upload_path, verbose_name='이미지')),
                ('category', models.IntegerField(blank=True, null=True, verbose_name='계절')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('like', models.IntegerField(default=0, verbose_name='좋아요')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'music',
            },
        ),
    ]
